merge_sort.cpp

A well commented merge sort code in C++
Time complexity: O(nlogn)

Merge Sort || C++|| O(nlogn)

---

quick_sort.cpp

Quick sort C++ code
Worst case time complexity: O(n^2)

Quick Sort || C++ || O(n^2)

---

Longest Increasing Subsequence .cpp

Longest Increasing Subsequence

---

bubbleSort.cpp

Added Bubble Sort

---

interpolation_search.cpp

Interpolation Search code in C++
Worst case time complexity: O(n)

Interpolation Search || C++ || O(n)

---

Sublist Search.cpp

Sublist Search

---

lcs.cpp

Fixed issue #27 
Longest common subsequence code in C++
Followed both top down and bottom up ways
Time complexity: O(n^2)

Longest common subsequence || C++ || O(n^2)

---

closest_pair.cpp

Closest pair algorithm can be used to find minimum distance of each pair of the points in O(n log n).

Add closest pair algorithm

---

Linear search algorithm

I had done the pull request please see.

Create Linear search algorithm

---

jump_search.cpp

Added Jump Search

---

bfsTraversal.cpp

Added BFS Algorithm

---

Heap sort .cpp

I created the pull request please see.

Create Heap sort .cpp

---

.vscode/settings.json
bogosort.cpp

Added BogoSort

---

Edit_Distance.cpp

Solution to LC 72. Edit Distance

---

LinearSearchAlgorithm.cpp

Linear Search is defined as a sequential search algorithm that starts at one end and goes through each element of a list until the desired element is found, otherwise the search continues till the end of the data set. It is the easiest searching algorithm

Linear Search algorithm

---

Z algorithm (Linear time pattern searching Algorithm)

This algorithm finds all occurrences of a pattern in a text in linear time. Let length of text be n and of pattern be m, then total time taken is O(m + n) with linear space complexity.

Z algorithm (Linear time pattern searching Algorithm)

---

inorder binary tree.cpp
level_order_traversal.cpp
print_nodeat_k_distance.cpp

Program 1: level order traversal of tree
Program 2: Print node at k distance
Program 3: Inorder traversal of Binary Tree

Tree Programs (DSA)

---

subsetSum.cpp

Subset Sum Problem

---

Advance_Euclid_Algorithm.cpp

Advance Euclid Algorithm

---

combinationSum.cpp

Given an array of positive integers arr[] and an integer x, The task is to find all unique combinations in arr[] where the sum is equal to x.

Combinational sum

---

selectionSort.cpp

Selection Sort

---

Diameter-of-a-Binary-Tree

The diameter of a binary tree is the length of the longest path between any two nodes in a tree. This path may or may not pass through the root. The length of a path between two nodes is represented by the number of edges between them.

Diameter-Binary-Tree.cpp

---

STL_find_max_min_vector.cpp

This algorithm ism used to find minimum and maximum element in a vector using inbuilt cpp functions.

STL_find_max_min_vector.cpp

---

dnf_sort.cpp

Given an array A[] consisting of only 0s, 1s, and 2s. The task is to write a function that sorts the given array. The functions should put all 0s first, then all 1s and all 2s in last.
This problem is also the same as the famous “Dutch National Flag problem”.

dnf_sort.cpp

---

append_k_nodes_to_start_of_linked_list.cpp

This algorithm is used to append last k nodes of a linked list to start of linked list

append_k_nodes_to_start_of_linked_list.cpp

---

Naive pattern.cpp
Rabin karp algorithm.cpp
fish pattern.cpp
optimized kmp.cpp

Initially calculate the hash value of the pattern.
Start iterating from the starting of the string:
Calculate the hash value of the current substring having length m.
If the hash value of the current substring and the pattern are same check if the substring is same as the pattern.
If they are same, store the starting index as a valid answer. Otherwise, continue for the next substrings.
Return the starting indices as the required answer.

Rabin Karp Algorithm

---

trie of all suffix.cpp

Building a Trie of Suffixes 
1) Generate all suffixes of given text. 
2) Consider all suffixes as individual words and build a trie.

trie of all suffix

---

count of number of string.cpp

To count all occurrences, we follow simple brute force approach. 
Traverse through each character of the matrix and taking each character as a start of the string to be found. 
Try to search in all the possible directions. 
Whenever, a word is found, increase the count.
After traversing the matrix what ever will be the value of count will be number of times string exists in character matrix.

count of number of string
